/* This file is auto-generated by scripts/generate-preview-manifest.mjs. */
import PreviewCancelObsoleteReportPreview from "../../tasks/async/cancel-obsolete-report-preview/main";
import PreviewFixCartSummaryState from "../../tasks/react/fix-cart-summary-state/main";
import PreviewFixStaleCustomerSearchResults from "../../tasks/async/fix-stale-customer-search-results/main";
import PreviewHandleUnknownAccountResponse from "../../tasks/api-integration/handle-unknown-account-response/main";

export const previewTaskSlugs = [
  "cancel-obsolete-report-preview",
  "fix-cart-summary-state",
  "fix-stale-customer-search-results",
  "handle-unknown-account-response"
] as const;

export function renderTaskPreviewFromManifest(slug: string) {
  switch (slug) {
    case "cancel-obsolete-report-preview":
      return <PreviewCancelObsoleteReportPreview />;
    case "fix-cart-summary-state":
      return <PreviewFixCartSummaryState />;
    case "fix-stale-customer-search-results":
      return <PreviewFixStaleCustomerSearchResults />;
    case "handle-unknown-account-response":
      return <PreviewHandleUnknownAccountResponse />;
    default:
      return null;
  }
}
