/* This file is auto-generated by scripts/generate-preview-manifest.mjs. */
import PreviewFixCartSummaryState from "../../tasks/react/fix-cart-summary-state/main";
import PreviewFixStaleCustomerSearchResults from "../../tasks/async/fix-stale-customer-search-results/main";

export const previewTaskSlugs = [
  "fix-cart-summary-state",
  "fix-stale-customer-search-results"
] as const;

export function renderTaskPreviewFromManifest(slug: string) {
  switch (slug) {
    case "fix-cart-summary-state":
      return <PreviewFixCartSummaryState />;
    case "fix-stale-customer-search-results":
      return <PreviewFixStaleCustomerSearchResults />;
    default:
      return null;
  }
}
