/* This file is auto-generated by scripts/generate-preview-manifest.mjs. */
import PreviewCompleteOrderRequestStateHandling from "../../tasks/api-integration/complete-order-request-state-handling/main";
import PreviewFixStaleAccountLookupResults from "../../tasks/async/fix-stale-account-lookup-results/main";
import PreviewOptimizeSearchableSelectionListRendering from "../../tasks/performance/optimize-searchable-selection-list-rendering/main";

export const previewTaskSlugs = [
  "complete-order-request-state-handling",
  "fix-stale-account-lookup-results",
  "optimize-searchable-selection-list-rendering"
] as const;

export function renderTaskPreviewFromManifest(slug: string) {
  switch (slug) {
    case "complete-order-request-state-handling":
      return <PreviewCompleteOrderRequestStateHandling />;
    case "fix-stale-account-lookup-results":
      return <PreviewFixStaleAccountLookupResults />;
    case "optimize-searchable-selection-list-rendering":
      return <PreviewOptimizeSearchableSelectionListRendering />;
    default:
      return null;
  }
}
